#!/usr/bin/env node
/**
 * compile-prompt.js — build the consulting system prompt FROM the Handbook.
 *
 * The book is the authoritative source; the prompt is a build artifact. Never hand-edit the
 * generated file. Change the book, rerun this, redeploy. That is what keeps the advice and the
 * published standard from drifting apart.
 *
 *   node method/compile-prompt.js [--check]
 *     writes ../site/lib/consulting-prompt.generated.js
 *     --check exits 1 if the file on disk differs from what the book would produce
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, '..', 'site', 'lib', 'consulting-prompt.generated.js');
const BOOK_URL = 'https://handbook.stacknative.ai';
const DONE_MARK = '[[READOUT]]';

// Pull the rubric out of chapter 4: everything from the first dimension heading through the
// end of the scoring rules. Headings are stripped to keep the prompt compact.
function rubric() {
  const md = fs.readFileSync(path.join(ROOT, 'book', '04-readiness-rubric.md'), 'utf8');
  const start = md.indexOf('## 1. Decision clarity');
  if (start < 0) throw new Error('rubric: dimension 1 heading not found');
  let body = md.slice(start).trim();
  body = body.replace(/^## /gm, '### ');              // demote, the template owns level 2
  body = body.replace(/^\*[^*].*\*$/gm, '');           // drop the italic asides for the consultant
  return body.replace(/\n{3,}/g, '\n\n').trim();
}

function version() {
  let sha = 'nogit';
  try { sha = execSync('git rev-parse --short HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch {}
  const v = (fs.readFileSync(path.join(ROOT, 'README.md'), 'utf8').match(/Version (\d+\.\d+)/) || [, '0.0'])[1];
  return `v${v} (${sha})`;
}

function build() {
  const tpl = fs.readFileSync(path.join(__dirname, 'prompt-template.md'), 'utf8');
  const text = tpl
    .replace(/\{\{RUBRIC\}\}/g, rubric())
    .replace(/\{\{VERSION\}\}/g, version())
    .replace(/\{\{BOOK_URL\}\}/g, BOOK_URL)
    .replace(/\{\{DONE_MARK\}\}/g, DONE_MARK)
    .trim();
  return `// GENERATED by handbook/method/compile-prompt.js — do not edit.\n`
    + `// Source: the AI-Native Operations Handbook. Change the book, not this file.\n`
    + `// Built ${new Date().toISOString().slice(0, 10)} from ${version()}\n`
    + `module.exports = {\n  SYSTEM: ${JSON.stringify(text)},\n  VERSION: ${JSON.stringify(version())},\n  DONE_MARK: ${JSON.stringify(DONE_MARK)},\n};\n`;
}

const out = build();
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  const strip = (s) => s.replace(/^\/\/ Built .*$/m, '');
  if (strip(cur) !== strip(out)) { console.error('consulting prompt is stale; run: node handbook/method/compile-prompt.js'); process.exit(1); }
  console.log('consulting prompt is current'); process.exit(0);
}
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log(`wrote ${OUT} (${out.length} bytes) from ${version()}`);
